"""create audit_log table

Revision ID: 72ee7f2c863c
Revises: 
Create Date: 2026-08-08 07:05:33.581653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ee7f2c863c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('EVENT', 'DECISION', 'EXECUTION', 'ANOMALY', name='auditcategory'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_category_occurred_at', 'audit_log', ['category', 'occurred_at'], unique=False)
    op.create_index('ix_audit_log_event_type', 'audit_log', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_event_type', table_name='audit_log')
    op.drop_index('ix_audit_log_category_occurred_at', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
